"""Add rich fields to Recommendation

Revision ID: aa3865fe1369
Revises: 
Create Date: 2026-06-29 12:56:37.905752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = 'aa3865fe1369'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendations', sa.Column('executive_summary', sa.Text(), nullable=True))
    op.add_column('recommendations', sa.Column('justification', mysql.JSON(), nullable=True))
    op.add_column('recommendations', sa.Column('missing_evidence', mysql.JSON(), nullable=True))
    op.add_column('recommendations', sa.Column('applicable_laws', mysql.JSON(), nullable=True))
    op.add_column('recommendations', sa.Column('detailed_applicable_laws', mysql.JSON(), nullable=True))
    op.add_column('recommendations', sa.Column('relevant_precedents', mysql.JSON(), nullable=True))
    op.add_column('recommendations', sa.Column('detailed_precedents', mysql.JSON(), nullable=True))
    op.add_column('recommendations', sa.Column('legal_risks', mysql.JSON(), nullable=True))
    op.add_column('recommendations', sa.Column('counterarguments', mysql.JSON(), nullable=True))
    op.add_column('recommendations', sa.Column('alternative_strategies', mysql.JSON(), nullable=True))
    op.add_column('recommendations', sa.Column('next_best_actions', mysql.JSON(), nullable=True))
    op.add_column('recommendations', sa.Column('expected_outcome', sa.Text(), nullable=True))
    op.add_column('recommendations', sa.Column('urgency', sa.String(length=100), nullable=True))
    op.add_column('recommendations', sa.Column('priority_explanation', sa.Text(), nullable=True))
    op.add_column('recommendations', sa.Column('confidence_explanation', sa.Text(), nullable=True))
    op.add_column('recommendations', sa.Column('risk_assessment', mysql.JSON(), nullable=True))
    op.add_column('recommendations', sa.Column('timeline', mysql.JSON(), nullable=True))
    op.add_column('recommendations', sa.Column('validation', mysql.JSON(), nullable=True))
    op.add_column('recommendations', sa.Column('contradictions', mysql.JSON(), nullable=True))
    op.add_column('recommendations', sa.Column('executive_opinion', mysql.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendations', 'executive_opinion')
    op.drop_column('recommendations', 'contradictions')
    op.drop_column('recommendations', 'validation')
    op.drop_column('recommendations', 'timeline')
    op.drop_column('recommendations', 'risk_assessment')
    op.drop_column('recommendations', 'confidence_explanation')
    op.drop_column('recommendations', 'priority_explanation')
    op.drop_column('recommendations', 'urgency')
    op.drop_column('recommendations', 'expected_outcome')
    op.drop_column('recommendations', 'next_best_actions')
    op.drop_column('recommendations', 'alternative_strategies')
    op.drop_column('recommendations', 'counterarguments')
    op.drop_column('recommendations', 'legal_risks')
    op.drop_column('recommendations', 'detailed_precedents')
    op.drop_column('recommendations', 'relevant_precedents')
    op.drop_column('recommendations', 'detailed_applicable_laws')
    op.drop_column('recommendations', 'applicable_laws')
    op.drop_column('recommendations', 'missing_evidence')
    op.drop_column('recommendations', 'justification')
    op.drop_column('recommendations', 'executive_summary')
    # ### end Alembic commands ###
